# Generated by Django 2.2.28 on 2023-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ewallet_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('trusted', models.BooleanField()),
            ],
        ),
    ]
